#ifndef HTTWSDDEVICE_GLOBAL_H
#define HTTWSDDEVICE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(HTTWSDDEVICE_LIBRARY)
#  define HTTWSDDEVICESHARED_EXPORT Q_DECL_EXPORT
#else
#  define HTTWSDDEVICESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // HTTWSDDEVICE_GLOBAL_H
